classdef EventEditWindow < handle
    %AnnoWindow Summary of this class goes here
    %   Detailed explanation goes here
    
    %Annotation Window allows you to View, Add, Edit and Delete Annotations
    
    %Author Tianxiao Jiang
    %Email  tjiang3@uh.edu
    
    properties
        event
        time
        comment
        fig
    end
    
    methods
        function obj=EventEditWindow(event,time)
            %Figure
            obj.fig=figure( 'MenuBar',              'none',...
                            'ToolBar',              'none',...
                            'position',             [400,200,150,300],...
                            'NumberTitle',          'off',...
                            'Name',                 '',...
                            'CloseRequestFcn',      @ (src,evts) delete(obj),...
                            'Resize',               'off',...
                            'DockControls',         'off');
            %text for event
            uicontrol(      'Parent',               obj.fig,...
                            'Style',                'text',...
                            'Units',                'normalized',...
                            'Position',             [0.01 0.9 0.98 0.06],...
                            'HorizontalAlignment',  'center',...
                            'String',               'Event:',...
                            'ForegroundColor',      [0.2 0.2 0.2],...
                            'FontSize',             12,...
                            'FontAngle',            'italic',...
                            'FontWeight',           'bold');
                        
            %editor for event
            uicontrol(      'Parent',               obj.fig,...
                            'Style',                'edit',...
                            'Units',                'normalized',...
                            'Position',             [0.01 0.69 0.98 0.2],...
                            'String',               event,...
                            'HorizontalAlignment',  'center',...
                            'Max',                  10,...
                            'Min',                  1,...
                            'FontSize',             12,...
                            'ForegroundColor',      [0.1 0.1 0.1]);
            
            %text for time            
            uicontrol(      'Parent',               obj.fig,...
                            'Style',                'text',...
                            'Units',                'normalized',...
                            'Position',             [0.01 0.61 0.98 0.06],...
                            'HorizontalAlignment',  'center',...
                            'String',               'Time (s) :',...
                            'ForegroundColor',      [0.2 0.2 0.2],...
                            'FontSize',             12,...
                            'FontAngle',            'italic',...
                            'FontWeight',           'bold');
            %editor for time           
            uicontrol(      'Parent',               obj.fig,...
                            'Style',                'edit',...
                            'Units',                'normalized',...
                            'Position',             [0.01 0.5 0.98 0.1],...
                            'String',               num2str(time),...
                            'FontSize',             12,...
                            'ForegroundColor',      [0.1 0.1 0.1]);
            
            %text for comment
            uicontrol(      'Parent',               obj.fig,...
                            'Style',                'text',...
                            'Units',                'normalized',...
                            'Position',             [0.01 0.42 0.98 0.06],...
                            'HorizontalAlignment',  'center',...
                            'String',               'Comment:',...
                            'ForegroundColor',      [0.2 0.2 0.2],...
                            'FontSize',             12,...
                            'FontAngle',            'italic',...
                            'FontWeight',           'bold');
             
            %editor fo comment            
            uicontrol(      'Parent',               obj.fig,...
                            'Style',                'edit',...
                            'Units',                'normalized',...
                            'Position',             [0.01 0.11 0.98 0.3],...
                            'String',               '',...
                            'HorizontalAlignment',  'left',...
                            'Max',                  10,...
                            'Min',                  1,...
                            'FontSize',             12,...
                            'ForegroundColor',      [0.1 0.1 0.1]);           
            %delete button            
            uicontrol(      'Parent',               obj.fig,...
                            'Style',                'pushbutton',...
                            'Units',                'normalized',...
                            'Position',             [0.01 0.01 0.3 0.1],...
                            'String',               'Delete',...
                            'ForegroundColor',      [0.1 0.1 0.1],...
                            'FontSize',             10);
                        
            %save button            
            uicontrol(      'Parent',               obj.fig,...
                            'Style',                'pushbutton',...
                            'Units',                'normalized',...
                            'Position',             [0.69 0.01 0.3 0.1],...
                            'String',               'Save',...
                            'ForegroundColor',      [0.2 0.2 0.2],...
                            'FontSize',             10);
            
            %left jump button
            uicontrol(      'Parent',               obj.fig,...
                            'Style',                'pushbutton',...
                            'Units',                'normalized',...
                            'Position',             [0.35 0.01 0.15 0.1],...
                            'String',               '<',...
                            'ForegroundColor',      [0.1 0.1 0.1],...
                            'FontSize',             10);
            
            %right jump button
            uicontrol(      'Parent',               obj.fig,...
                            'Style',                'pushbutton',...
                            'Units',                'normalized',...
                            'Position',             [0.5 0.01 0.15 0.1],...
                            'String',               '>',...
                            'ForegroundColor',      [0.2 0.2 0.2],...
                            'FontSize',             10);
                            
                        
        end
        
        function delete(obj)
            h=obj.fig;
            notify(obj,'EvtEditClose');
            if ishandle(h)
                delete(h);
            else
                return
            end
        end
        
    end
    
    events
        EvtEditClose
    end
end

