classdef EventEditWindow
    %AnnoWindow Summary of this class goes here
    %   Detailed explanation goes here
    
    %Annotation Window allows you to View, Add, Edit and Delete Annotations
    
    %Author Tianxiao Jiang
    %Email  tjiang3@uh.edu
    
    properties
        Event
        Time
        EventIndex
        Comment
        Fig
        EventEditHandle
        TimeEditHandle
    end
    
    methods
        function obj=EventEditWindow(bsp)
            
            EI=bsp.SelectedEvent;
            
            EventList=bsp.Evts;
            obj.Event=EventList{EI,2};
            obj.Time=EventList{EI,1};
            obj.EventIndex=EI;
            
            %Figure
            obj.Fig=figure( 'MenuBar',              'none',...
                            'ToolBar',              'none',...
                            'position',             [400,200,150,300],...
                            'NumberTitle',          'off',...
                            'Name',                 '',...
                            'CloseRequestFcn',      @ (src,evts) delete(obj),...
                            'Resize',               'off',...
                            'DockControls',         'off');
            %text for event
            uicontrol(      'Parent',               obj.Fig,...
                            'Style',                'text',...
                            'Units',                'normalized',...
                            'Position',             [0.01 0.9 0.98 0.06],...
                            'HorizontalAlignment',  'center',...
                            'String',               'Event:',...
                            'ForegroundColor',      [0.2 0.2 0.2],...
                            'FontSize',             12,...
                            'FontAngle',            'italic',...
                            'FontWeight',           'bold');
                        
            %editor for event
            obj.EventEditHandle=...
            uicontrol(      'Parent',               obj.Fig,...
                            'Style',                'edit',...
                            'Units',                'normalized',...
                            'Position',             [0.01 0.69 0.98 0.2],...
                            'String',               obj.Event,...
                            'HorizontalAlignment',  'center',...
                            'Max',                  10,...
                            'Min',                  1,...
                            'FontSize',             12,...
                            'ForegroundColor',      [0.1 0.1 0.1]);
            
            %text for time            
            uicontrol(      'Parent',               obj.Fig,...
                            'Style',                'text',...
                            'Units',                'normalized',...
                            'Position',             [0.01 0.61 0.98 0.06],...
                            'HorizontalAlignment',  'center',...
                            'String',               'Time (s) :',...
                            'ForegroundColor',      [0.2 0.2 0.2],...
                            'FontSize',             12,...
                            'FontAngle',            'italic',...
                            'FontWeight',           'bold');
            %editor for time           
            obj.TimeEditHandle=...
            uicontrol(      'Parent',               obj.Fig,...
                            'Style',                'edit',...
                            'Units',                'normalized',...
                            'Position',             [0.01 0.5 0.98 0.1],...
                            'String',               num2str(obj.Time),...
                            'FontSize',             12,...
                            'ForegroundColor',      [0.1 0.1 0.1]);
            
            %text for comment
            uicontrol(      'Parent',               obj.Fig,...
                            'Style',                'text',...
                            'Units',                'normalized',...
                            'Position',             [0.01 0.42 0.98 0.06],...
                            'HorizontalAlignment',  'center',...
                            'String',               'Comment:',...
                            'ForegroundColor',      [0.2 0.2 0.2],...
                            'FontSize',             12,...
                            'FontAngle',            'italic',...
                            'FontWeight',           'bold');
             
            %editor fo comment            
            uicontrol(      'Parent',               obj.Fig,...
                            'Style',                'edit',...
                            'Units',                'normalized',...
                            'Position',             [0.01 0.11 0.98 0.3],...
                            'String',               '',...
                            'HorizontalAlignment',  'left',...
                            'Max',                  10,...
                            'Min',                  1,...
                            'FontSize',             12,...
                            'ForegroundColor',      [0.1 0.1 0.1]);           
            %delete button            
            uicontrol(      'Parent',               obj.Fig,...
                            'Style',                'pushbutton',...
                            'Units',                'normalized',...
                            'Position',             [0.01 0.01 0.3 0.1],...
                            'String',               'Delete',...
                            'ForegroundColor',      [0.1 0.1 0.1],...
                            'FontSize',             10,...
                            'callback',             {@EventContexMenu.eventDelete,bsp});
                        
            %save button            
            uicontrol(      'Parent',               obj.Fig,...
                            'Style',                'pushbutton',...
                            'Units',                'normalized',...
                            'Position',             [0.69 0.01 0.3 0.1],...
                            'String',               'Save',...
                            'ForegroundColor',      [0.2 0.2 0.2],...
                            'FontSize',             10,...
                            'callback',             {@eventSave,bsp});
            
            %left jump button
            uicontrol(      'Parent',               obj.Fig,...
                            'Style',                'pushbutton',...
                            'Units',                'normalized',...
                            'Position',             [0.35 0.01 0.15 0.1],...
                            'String',               '<',...
                            'ForegroundColor',      [0.1 0.1 0.1],...
                            'FontSize',             10);
            
            %right jump button
            uicontrol(      'Parent',               obj.Fig,...
                            'Style',                'pushbutton',...
                            'Units',                'normalized',...
                            'Position',             [0.5 0.01 0.15 0.1],...
                            'String',               '>',...
                            'ForegroundColor',      [0.2 0.2 0.2],...
                            'FontSize',             10);
                            
                        
        end
        
        
    end
    
    methods(Static)
        function eventSave(src,evt,bsp)
            EventList=bsp.Evts;
            
            NewEvent=get(obj.EventEditHandle,'String');
            NewTime=str2double(get(obj.TimeEditHandle,'String'));
            
            EventList{obj.EventIndex,1}=NewTime;
            EventList{obj.EventIndex,2}=NewEvent;
            
            [t,IX]=sort(EventList(:,1));
            
            for i=1:size(EventList,1)
                SortedEventList{i,1}=EventList{IX(i),1};
                SortedEventList{i,2}=EventList{IX(i),2};
                if IX(i)==obj.EventIndex
                    obj.EventIndex=i;
                end
            end
            
            bsp.Evts=SortedEventList;
            
        end
    end
end

