function timeControlPanel(obj,parent,position)
obj.TimePanel=uipanel(parent,'units','normalized','position',position);
obj.BtnPrevPage=uicontrol(obj.TimePanel,'Style','pushbutton','String','<<',...
    'units','normalized','position',[.01 .1 .1 .8],'Callback',@(src,evt) ChangeTime(obj,src),...
    'TooltipString','one-page backward    shift left');
obj.BtnPrevSec=uicontrol(obj.TimePanel,'Style','pushbutton','String','<',...
    'units','normalized','position',[.11 .1 .1 .8],'Callback',@(src,evt) ChangeTime(obj,src),...
    'TooltipString','one-second backward    ctrl left');
obj.EdtTime=uicontrol(obj.TimePanel,'Style','edit','String',0,'units','normalized',...
    'position',[.22 0.1 .26 .8],'BackgroundColor',[1 1 1],'Callback',@(src,evt) ChangeTime(obj,src),...
    'TooltipString','page start time');
obj.BtnNextSec=uicontrol(obj.TimePanel,'Style','pushbutton','String','>',...
    'units','normalized','position',[.49 0.1 .1 .8],'Callback',@(src,evt) ChangeTime(obj,src),...
    'TooltipString','one-second forward    ctrl right');
obj.BtnNextPage=uicontrol(obj.TimePanel,'Style','pushbutton','String','>>',...
    'units','normalized','position',[.60 0.1 .1 .8],'Callback',@(src,evt) ChangeTime(obj,src),...
    'TooltipString','one-page forward    shift right');
obj.BtnPlay=uicontrol(obj.TimePanel,'Style','pushbutton','String','Play',...
    'units','normalized','position',[.71 0.1 .28 .8],'Callback',@(src,evt) StartPlay(obj));
end