function timeControlPanel(obj,parent,position)

obj.TimePanel=uipanel(parent,'units','normalized','position',position);

obj.BtnPrevEvent=uicontrol(obj.TimePanel,'Style','pushbutton','String','|<',...
    'units','normalized','position',[0.02 0.1 0.09 0.8],'Callback',@(src,evt) ChangeTime(obj,src),...
    'TooltipString','backward by event');

obj.BtnPrevPage=uicontrol(obj.TimePanel,'Style','pushbutton','String','<<',...
    'units','normalized','position',[.15 .1 .09 .8],'Callback',@(src,evt) ChangeTime(obj,src),...
    'TooltipString','one-page backward    shift left');
obj.BtnPrevSec=uicontrol(obj.TimePanel,'Style','pushbutton','String','<',...
    'units','normalized','position',[.25 .1 .09 .8],'Callback',@(src,evt) ChangeTime(obj,src),...
    'TooltipString','one-second backward    ctrl left');
obj.EdtTime=uicontrol(obj.TimePanel,'Style','edit','String',0,'units','normalized',...
    'position',[.35 0.1 .3 .8],'BackgroundColor',[1 1 1],'Callback',@(src,evt) ChangeTime(obj,src),...
    'TooltipString','page start time');
obj.BtnNextSec=uicontrol(obj.TimePanel,'Style','pushbutton','String','>',...
    'units','normalized','position',[.66 0.1 .09 .8],'Callback',@(src,evt) ChangeTime(obj,src),...
    'TooltipString','one-second forward    ctrl right');
obj.BtnNextPage=uicontrol(obj.TimePanel,'Style','pushbutton','String','>>',...
    'units','normalized','position',[0.76 0.1 .09 .8],'Callback',@(src,evt) ChangeTime(obj,src),...
    'TooltipString','one-page forward    shift right');

obj.BtnNextEvent=uicontrol(obj.TimePanel,'Style','pushbutton','String','>|',...
    'units','normalized','position',[0.89 0.1 0.09 0.8],'Callback',@(src,evt) ChangeTime(obj,src),...
    'TooltipString','forward by event');
end