
function toolToolbar(obj)

obj.BtnWidthIncrease=uipushtool(obj.Toolbar,'CData',imread('widthIncrease.bmp'),'TooltipString','Increase width','separator','on',...
    'ClickedCallback',@(src,evt) ChangeDuration(obj,src));

obj.BtnWidthDecrease=uipushtool(obj.Toolbar,'CData',imread('widthDecrease.bmp'),'TooltipString','Decrease width',...
    'ClickedCallback',@(src,evt) ChangeDuration(obj,src));

obj.BtnHeightIncrease=uipushtool(obj.Toolbar,'CData',imread('heightIncrease.bmp'),'TooltipString','Increase height',...
    'ClickedCallback',@(src,evt) ChangeChan(obj,src));

obj.BtnHeightDecrease=uipushtool(obj.Toolbar,'CData',imread('heightDecrease.bmp'),'TooltipString','Decrease height',...
    'ClickedCallback',@(src,evt) ChangeChan(obj,src));

obj.TogMeasurer=uitoggletool(obj.Toolbar,'CData',imread('measurer.bmp'),'TooltipString','Measure of each channels','separator','on',...
    'ClickedCallback',@(src,evt) ChangeMouseMode(obj,src));

obj.TogSelection=uitoggletool(obj.Toolbar,'CData',imread('select.bmp'),'TooltipString','Selection(ctrl e)','separator','on',...
    'ClickedCallback',@(src,evt) ChangeMouseMode(obj,src));
obj.BtnTFMap=uipushtool(obj.Toolbar,'CData',imread('tfmap.bmp'),'TooltipString','Time-Frequency map',...
    'ClickedCallback',@(src,evt) Time_Freq_Map(obj,src));

obj.TogAnnotate=uitoggletool(obj.Toolbar,'CData',imread('evts.bmp'),'TooltipString','Insert events(ctrl i)','separator','on',...
    'ClickedCallback',@(src,evt) ChangeMouseMode(obj,src));

obj.BtnGainIncrease=uipushtool(obj.Toolbar,'CData',imread('plus.bmp'),'TooltipString','Increase gain (ctrl =)','separator','on',...
    'ClickedCallback',@(src,evt) ChangeGain(obj,src));

obj.BtnGainDecrease=uipushtool(obj.Toolbar,'CData',imread('minus.bmp'),'TooltipString','Decrease gain (ctrl -)',...
    'ClickedCallback',@(src,evt) ChangeGain(obj,src));
end